#!/usr/bin/env zsh

curl -sSL https://github.com/scottchiefbaker/dool/archive/refs/tags/v1.3.1.tar.gz -o v1.3.1.tar.gz
tar -zxvf v1.3.1.tar.gz
cd dool-1.3.1 && sudo ./install.py

rm v1.3.1.tar.gz
rm -rf dool-1.3.1
