#!/usr/bin/env zsh

osName=`uname -s`;

if [[ $osName = "Darwin" ]]; then
  cd $HOME
  brew update;
  brew link autoconf;
  brew install rbenv ruby-build;
fi

if [[ $osName = "Linux" ]]; then

# 値が1だったらCentOS 0だったらUbuntu
linuxDistoribution=`cat /proc/version | grep "Red Hat" | wc -l`;

if [[ $linuxDistoribution -eq 0 ]]; then
    sudo apt-get update;
    sudo apt-get -y install git curl g++ make;
    sudo apt-get -y install zlib1g-dev libssl-dev libreadline-dev;
    sudo apt-get -y install libyaml-dev libxml2-dev libxslt-dev;
  fi

  if [[ $linuxDistoribution -eq 1 ]]; then
    sudo yum install -y git gcc gcc-c++ openssl-devel readline-devel;
  fi

  git clone git@github.com:sstephenson/rbenv.git ~/.rbenv;
  mkdir -p ~/.rbenv/plugins;
  cd ~/.rbenv/plugins;
  git clone git@github.com:sstephenson/ruby-build.git;
fi
