#!/usr/bin/env zsh

git clone https://github.com/phpenv/phpenv.git ~/.phpenv
git clone https://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build

echo 'export PATH="$HOME/.phpenv/bin:$PATH"' >> ~/.profile
echo 'eval "$(phpenv init -)"' >> ~/.profile
