#!/usr/bin/env zsh

curl -sSL https://github.com/scottchiefbaker/dool/archive/refs/tags/v1.3.1.tar.gz -o v1.3.1.tar.gz || { echo "Download failed"; exit 1; }
tar -zxvf v1.3.1.tar.gz || { echo "Extraction failed"; exit 1; }
cd dool-1.3.1 && sudo ./install.py || { echo "Installation failed"; exit 1; }

rm v1.3.1.tar.gz
rm -rf dool-1.3.1
