#!/bin/zsh

# 既にあれば削除して再度張り直す
for rc in gemrc gitconfig screenrc tmux.conf tmux-powerlinerc zshrc vim vimrc
do
  rm -f ~/.$rc && ln -s ~/dotfiles/$rc ~/.$rc
done

mkdir -p ~/.vim/pack/git-plugins/start
git clone https://github.com/w0rp/ale.git ~/.vim/pack/git-plugins/start/ale

rm -f ~/.vimshrc && ln -s ~/dotfiles/zshrc.alias ~/.vimshrc

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
sh ./installer.sh ~/.cache/dein

# pyenv + plenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
git clone https://github.com/tokuhirom/plenv.git ~/.plenv

# tmuxとMacのクリップボードを共有できるようにする
uname=`uname -s`;
if [[ $uname -eq "Darwin" ]]; then
  brew install reattach-to-user-namespace
fi

# tmux powerline
rm -rf ~/dotfiles/tmux/tmux-powerline
git clone https://github.com/erikw/tmux-powerline ~/dotfiles/tmux/tmux-powerline
ln -s ~/dotfiles/tmux/my-tmux-powerline/themes/mytheme.sh ~/dotfiles/tmux/tmux-powerline/themes/mytheme.sh
patch -u ~/dotfiles/tmux/tmux-powerline/segments/vcs_branch.sh < ~/dotfiles/tmux/my-tmux-powerline/segments/vcs_branch.patch

# zplug
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
