[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'shelling/railscasts.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'jacoborus/tender.vim'
