[[plugins]]
repo = 'mattn/vim-starwars' # :StarWars

[[plugins]]
repo = 'c9s/helper.vim'     # for VKube

[[plugins]]
repo = 'c9s/treemenu.vim'   # for VKube

[[plugins]]
repo = 'c9s/vikube.vim'     # for VKube

[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "ruby", "go"]
build = "./install_gadget.py --enable-python --enable-ruby --enable-go --update-gadget-config"
