[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# 入れるとか入れないとかそういう類の物では無い
repo = 'scrooloose/nerdtree'
repo = 'tpope/vim-fugitive'
repo = 'bling/vim-airline'
repo = 'Shougo/unite.vim'

[[plugins]]
# colorschemeをアドホックに
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
# syntax highligh関連
repo = 'fatih/vim-go'
on_ft = ['go']
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']
repo = 'elixir-lang/vim-elixir'


[[plugins]]
# 便利プラグインとか
repo = 'w0rp/ale'                      # syntaxチェックをしてくれる(対応言語めっちゃ大量)
repo = 'airblade/vim-gitgutter'        # 編集の差分表示をしてくれる
repo = 'alpaca-tc/vim-endwise'         # 最後のendやカッコを勝手に付けてくれるやつ
repo = 'godlygeek/tabular'             # イコールの位置を揃えたい時とかに使うやつ
repo = 'banyan/recognize_charcode.vim' # 文字コードの自動認識
repo = 'thinca/vim-quickrun'           # vim内部でプログラム実行
