[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# 入れるとか入れないとかそういう類の物では無い
repo = 'scrooloose/nerdtree'
repo = 'tpope/vim-fugitive'
repo = 'bling/vim-airline'
repo = 'Shougo/unite.vim'

[[plugins]]
# colorschemeをアドホックに
repo = 'ujihisa/unite-colorscheme'
repo = 'fatih/vim-go'
on_ft = ['go']
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']
repo = 'elixir-lang/vim-elixir'
# 最後のendやカッコを勝手に付けてくれるやつ
repo = 'alpaca-tc/vim-endwise'
