[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'ts']

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'fgsch/vim-varnish'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'bazelbuild/vim-bazel'

[[plugins]]
repo = 'nikvdp/ejs-syntax'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'tomlion/vim-solidity'
